Name: locust
image:
  repository: quay.io/honestbee/locust
  tag: 0.7.5
  pullPolicy: IfNotPresent
  
  
service:
  name: master-web
  type: NodePort
  externalPort: 8089
  internalPort: 8089
  nodePort: 0
  annotations: {}
  extraLabels: {}
  
master:
  config:
    # ingress의 경우에는 ingress의 domain을 지정해준다
    # target가 pod인경우 pod의 경우에는 kubernetes cluster ip를 지정해준다(ex) kubectl get svc 의 Cluster IP)
    target-host: http://10.104.1.247:3000
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
  
  
worker:
  config:
    # all files from tasks folder are mounted under `/locust-tasks`
    locust-script: "/locust-tasks/tasks.py"
  # 많은 부하를 주고싶으면 아래 수치를 조정 2000rps정도면 50개 생성
  replicaCount: 50 
  #resources:
  #  limits:
  #    memory: 128Mi
  #  requests:
  #    memory: 128Mi
